name: Validate Python projects
on: 
  pull_request:
    branches:
        - doc-samples
jobs:
  validate:
    name: Validate Python project
    runs-on: ubuntu-latest
    container: python:3.7
    strategy:
      matrix:
        project-directory:
          - ./001-quickstart
          - ./101-client-connection-string
          - ./200-admin
          - ./201-does-database-exist
          - ./202-get-doc-count
          - ./300-drop-database
    defaults:
      run:
        working-directory: ${{ matrix.project-directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Check Python version
        run: python --version
      - name: Install packages
        run: pip install black flake8
      - name: Lint with flake8
        run: flake8 --count --verbose run.py
      - name: Check format with black
        run: black --check --verbose --line-length 79 run.py